name: Build FoxicMP

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'
      - '**.txt'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.txt'

jobs:
  build:
    runs-on: windows-2022
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Prepare MSYS
        run: |
          curl -sSL https://github.com/Aleksoid1978/MSYS/raw/main/MSYS_MinGW-w64_GCC_1521_x86-x64.7z -o MSYS.7z
          7z x MSYS.7z -oC:\MSYS
          echo '@ECHO OFF' > environments.bat
          echo 'SET "FOXICMP_MSYS=C:\MSYS"' >> environments.bat
          echo 'SET "FOXICMP_MINGW=C:\MSYS\mingw"' >> environments.bat
          .\update_gcc.bat
        shell: pwsh

      - name: Clean
        run: .\build.bat Clean All NoWait
        shell: pwsh

      - name: Build FoxicMP
        run: .\build.bat Build Packages NoWait
        shell: pwsh

      - name: Upload x64 packages
        uses: actions/upload-artifact@v7
        with:
          name: FoxicMP-x64
          path: |
            _bin/Packages/**/FoxicMP*.x64-installer.zip
            _bin/Packages/**/FoxicMP*.x64.7z
            _bin/Packages/**/FoxicMP*.x64.zip
          if-no-files-found: error
          compression-level: 0

      - name: Upload x86 packages
        uses: actions/upload-artifact@v7
        with:
          name: FoxicMP-x86
          path: |
            _bin/Packages/**/FoxicMP*.x86-installer.zip
            _bin/Packages/**/FoxicMP*.x86.7z
            _bin/Packages/**/FoxicMP*.x86.zip
          if-no-files-found: error
          compression-level: 0
